namespace SPTarkov.Server.Core.Models.Enums;

public enum BackendErrorCodes
{
    None,
    UnknownError = 200,
    NotAuthorized,
    NeedAuthorizationCode = 209,
    WrongAuthorizationCode = 211,
    NeedCaptcha = 214,
    NoNeedCaptcha,
    CaptchaInvalidAnswer,
    CaptchaFailed = 218,
    CaptchaBruteForced,
    NoRoomInStash = 223,
    NicknameNotUnique = 225,
    NicknameNotValid,
    UnsupportedClientVersion = 232,
    ReportNotAllowed = 238,
    NicknameIsAbusive = 241,
    NicknameChangeTimeout,
    NotEnoughSpaceToUnpack = 257,
    NotModified = 304,
    HTTPBadRequest = 400,
    HTTPNotAuthorized,
    HTTPForbidden = 403,
    HTTPNotFound,
    HTTPMethodNotAllowed,
    UnknownTradingError = 500,
    HTTPNotImplemented,
    HTTPBadGateway,
    HTTPServiceUnavailable,
    HTTPGatewayTimeout,
    TraderOutOfMoney,
    HTTPVariantAlsoNegotiates,
    PriceChanged = 509,
    TraderDisabled = 512,
    ItemHasBeenSold,
    NotEnoughSpaceForMoney = 518,
    HTTPInvalidSSLCertificate = 526,
    UnknownRagfairError = 550,
    UnknownRagfairError2,
    UnknownMatchMakerError = 600,
    SessionParametersError,
    SessionLost,
    ServerNotRegistered = 604,
    UnknownQuestError = 700,
    QuestBadParam = 702,
    QuestNotFound,
    QuestIsUnavailable,
    NoFreeSpaceForRewards,
    WrongQuestStatus,
    CantCompleteQuest,
    UnknownMailError = 900,
    TooManyFriendRequests = 925,
    UnknownScriptExecutionError = 1000,
    UnknownRepairingError = 1200,
    UnknownInsuranceError = 1300,
    UnknownCurrencyExchangeError = 1400,
    OfferNotFound = 1503,
    NotEnoughSpace = 1505,
    OfferOutOfStock,
    OfferSold,
    RagfairUnavailable = 1511,
    BannedErrorCode = 1513,
    InsufficientNumberInStock = 1516,
    TooManyItemsToSell,
    IncorrectClientPrice = 1519,
    ExaminationFailed = 22001,
    ItemAlreadyExamined,
    UnknownNginxError = 9000,
    ParseResponseError,
    UnknownMatchmakerError = 503000,
    UnknownGroupError = 502000,
    GroupRequestNotFound = 502002,
    GroupFull = 502004,
    PlayerAlreadyInGroup,
    PlayerNotInGroup,
    PlayerNotLeader,
    CantChangeReadyState = 502010,
    PlayerForbiddenGroupInvites,
    LeaderAlreadyReady,
    GroupSendInviteError,
    PlayerIsOffline,
    PlayerIsNotSearchingForGroup = 502018,
    PlayerTooManyPartyRequests = 502021,
    PlayerIsInRegularMode = 502032,
    PlayerIsInPveMode,
    PlayerAlreadyLookingForGame = 503001,
    PlayerInRaid,
    LimitForPresetsReached = 504001,
    PlayerProfileNotFound = 505001,
    NoArenaSync = 507006,
}
