namespace SPTarkov.Server.Core.Models.Enums;

public enum RewardType
{
    Experience,
    Skill,
    Item,
    TraderStanding,
    TraderUnlock,
    Location,
    Counter,
    AssortmentUnlock,
    ProductionScheme,
    TraderStandingReset,
    TraderStandingRestore,
    StashRows,
    Achievement,
    Pockets,
    Quest,
    CustomizationOffer,
    ExtraDailyQuest,
    CustomizationDirect,
    Stub,
    WebPromoCode,
    NotificationPopup,
    Customization = 116,
    BattlePassExperience,
    BattlePassCurrency,
    ArenaArmoryItem = 100,
}
