using System.Text.Json.Serialization;

namespace SPTarkov.Server.Core.Models.Enums;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum SkillTypes
{
    Endurance,
    Strength,
    Vitality,
    Health,
    StressResistance,
    Metabolism,
    Immunity,
    Perception,
    Intellect,
    Attention,
    Charisma = 10,
    Memory,
    MagDrills,
    Pistol,
    Revolver,
    SMG,
    Assault,
    Shotgun,
    Sniper,
    LMG,
    HMG,
    Launcher,
    AttachedLauncher,
    Throwing,
    Misc,
    Melee,
    DMR,
    DrawMaster,
    AimMaster,
    RecoilControl,
    TroubleShooting,
    Sniping,
    CovertMovement,
    ProneMovement,
    FirstAid,
    FieldMedicine,
    Surgery,
    LightVests,
    HeavyVests,
    WeaponModding,
    AdvancedModding,
    NightOps,
    SilentOps,
    Lockpicking,
    Search,

    // Also called Weapon Maintenance
    WeaponTreatment,
    Freetrading,
    Auctions,
    Cleanoperations,
    Barter,
    Shadowconnections,
    Taskperformance,
    BearAssaultoperations,
    BearAuthority,
    BearAksystems,
    BearHeavycaliber,
    BearRawpower,
    UsecArsystems,
    UsecDeepweaponmodding,
    UsecLongrangeoptics,
    UsecNegotiations,
    UsecTactics,
    BotReload,
    BotSound,
    AimDrills,
    HideoutManagement,
    Crafting = 66,
}
