namespace SPTarkov.Server.Core.Models.Enums.Hideout;

public enum HideoutAreas
{
    NotSet = -1,
    Vents,
    Security,
    WaterCloset,
    Stash,
    Generator,
    Heating,
    WaterCollector,
    MedStation,
    Kitchen,
    RestSpace,
    Workbench,
    IntelligenceCenter,
    ShootingRange,
    Library,
    ScavCase,
    Illumination,
    PlaceOfFame,
    AirFilteringUnit,
    SolarPower,
    BoozeGenerator,
    BitcoinFarm,
    ChristmasIllumination,
    EmergencyWall,
    Gym,
    WeaponStand,
    WeaponStandSecondary,
    EquipmentPresetsStand,
    CircleOfCultists,
}
